// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.20.1
// source: hatmaker.proto

package hatmaker

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// HatmakerClient is the client API for Hatmaker service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type HatmakerClient interface {
	// MakeHat produces a hat of mysterious, randomly-selected color!
	MakeHat(ctx context.Context, in *Size, opts ...grpc.CallOption) (*Hat, error)
}

type hatmakerClient struct {
	cc grpc.ClientConnInterface
}

func NewHatmakerClient(cc grpc.ClientConnInterface) HatmakerClient {
	return &hatmakerClient{cc}
}

func (c *hatmakerClient) MakeHat(ctx context.Context, in *Size, opts ...grpc.CallOption) (*Hat, error) {
	out := new(Hat)
	err := c.cc.Invoke(ctx, "/hatmaker.Hatmaker/MakeHat", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HatmakerServer is the server API for Hatmaker service.
// All implementations must embed UnimplementedHatmakerServer
// for forward compatibility
type HatmakerServer interface {
	// MakeHat produces a hat of mysterious, randomly-selected color!
	MakeHat(context.Context, *Size) (*Hat, error)
	mustEmbedUnimplementedHatmakerServer()
}

// UnimplementedHatmakerServer must be embedded to have forward compatible implementations.
type UnimplementedHatmakerServer struct {
}

func (UnimplementedHatmakerServer) MakeHat(context.Context, *Size) (*Hat, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MakeHat not implemented")
}
func (UnimplementedHatmakerServer) mustEmbedUnimplementedHatmakerServer() {}

// UnsafeHatmakerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to HatmakerServer will
// result in compilation errors.
type UnsafeHatmakerServer interface {
	mustEmbedUnimplementedHatmakerServer()
}

func RegisterHatmakerServer(s grpc.ServiceRegistrar, srv HatmakerServer) {
	s.RegisterService(&Hatmaker_ServiceDesc, srv)
}

func _Hatmaker_MakeHat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Size)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HatmakerServer).MakeHat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/hatmaker.Hatmaker/MakeHat",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HatmakerServer).MakeHat(ctx, req.(*Size))
	}
	return interceptor(ctx, in, info, handler)
}

// Hatmaker_ServiceDesc is the grpc.ServiceDesc for Hatmaker service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Hatmaker_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "hatmaker.Hatmaker",
	HandlerType: (*HatmakerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "MakeHat",
			Handler:    _Hatmaker_MakeHat_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "hatmaker.proto",
}
