package dashboard

const dashboardAPI = "/dashboard"
const validateKeyAPI = "/api/key/validate"
const usersListGetAPI = "/api/users"
const usersCountAPI = "/api/users/count"
const userAPI = "/api/user"
const userEmailVerifyAPI = "/api/user/email/verify"
const userSessionsAPI = "/api/user/sessions"
const userMetaDataAPI = "/api/user/metadata"
const userEmailVerifyTokenAPI = "/api/user/email/verify/token"
const userPasswordAPI = "/api/user/password"
const signInAPI = "/api/signin"
const signOutAPI = "/api/signout"
const dashboardAnalyticsAPI = "/api/analytics"
