name: "Pre commit hook check"

on:
    pull_request:
        types:
            - opened
            - reopened
            - edited
            - synchronize

jobs:
    pr-title:
        name: Pre commit hook check
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Set up go
              uses: actions/setup-go@v5
              with:
                go-version: '1.18'
            - run: rm -rf .git && git init && git add --all && git -c user.name='test' -c user.email='test@example.com' commit -m 'init for pr action'
            - run: ./hooks/pre-commit.sh
